# Generated by Django 3.1.1 on 2020-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
