# Generated by Django 3.1.1 on 2020-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cancion_estilo_interprete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='popularidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
