# Generated by Django 3.1.1 on 2020-11-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cancion_popularidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
