# Generated by Django 3.1.1 on 2020-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='popularidad_estilo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
